[package]
name = "machine-learning-starter"
version = "0.1.0"
authors = ["Subhobrata Dey <sbcd90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.5"
rand = "0.8.0"

